// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyWeatherApp.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyWeatherApp.Migrations
{
    [DbContext(typeof(WeatherDbContext))]
    partial class WeatherDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyWeatherApp.Models.Application", b =>
                {
                    b.Property<int>("AppId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AppId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AppId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("MyWeatherApp.Models.Forecast", b =>
                {
                    b.Property<int>("ForecastId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ForecastId"));

                    b.Property<int>("AppId")
                        .HasColumnType("integer");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<double>("PredTemp")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("RetrievedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("TargetDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ForecastId");

                    b.HasIndex("LocationId");

                    b.HasIndex("AppId", "LocationId", "TargetDateTime")
                        .IsUnique();

                    b.ToTable("Forecasts");
                });

            modelBuilder.Entity("MyWeatherApp.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LocationId"));

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObservationStationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("MyWeatherApp.Models.Observation", b =>
                {
                    b.Property<int>("ObsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ObsId"));

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ObsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Temp")
                        .HasColumnType("double precision");

                    b.HasKey("ObsId");

                    b.HasIndex("LocationId", "ObsAt")
                        .IsUnique();

                    b.ToTable("Observations");
                });

            modelBuilder.Entity("MyWeatherApp.Models.Forecast", b =>
                {
                    b.HasOne("MyWeatherApp.Models.Application", "Application")
                        .WithMany("Forecasts")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyWeatherApp.Models.Location", "Location")
                        .WithMany("Forecasts")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("MyWeatherApp.Models.Observation", b =>
                {
                    b.HasOne("MyWeatherApp.Models.Location", "Location")
                        .WithMany("Observations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("MyWeatherApp.Models.Application", b =>
                {
                    b.Navigation("Forecasts");
                });

            modelBuilder.Entity("MyWeatherApp.Models.Location", b =>
                {
                    b.Navigation("Forecasts");

                    b.Navigation("Observations");
                });
#pragma warning restore 612, 618
        }
    }
}
